
# Set architecture paths for the OPENCMISS Build.

set(ARCHITECTURE_PATH .)
set(ARCHITECTURE_PATH_MPI .)
if (OC_USE_ARCHITECTURE_PATH)
    getArchitecturePath(ARCHITECTURE_PATH ARCHITECTURE_PATH_MPI)
endif()

# Build tree locations for components (with/without mpi)
if (DEFINED OPENCMISS_ROOT)
  set(OPENCMISS_COMPONENTS_BINARY_DIR "${OPENCMISS_ROOT}/build/${ARCHITECTURE_PATH}")
  set(OPENCMISS_COMPONENTS_BINARY_DIR_MPI "${OPENCMISS_ROOT}/build/${ARCHITECTURE_PATH_MPI}")
  set(OPENCMISS_LIBRARIES_BINARY_DIR "${OPENCMISS_ROOT}/build/${ARCHITECTURE_PATH}")
  set(OPENCMISS_LIBRARIES_BINARY_DIR_MPI "${OPENCMISS_ROOT}/build/${ARCHITECTURE_PATH_MPI}")
else ()
  set(OPENCMISS_COMPONENTS_BINARY_DIR "${OPENCMISS_DEPENDENCIES_ROOT}/build/${ARCHITECTURE_PATH}")
  set(OPENCMISS_COMPONENTS_BINARY_DIR_MPI "${OPENCMISS_DEPENDENCIES_ROOT}/build/${ARCHITECTURE_PATH_MPI}")
  set(OPENCMISS_LIBRARIES_BINARY_DIR "${OPENCMISS_LIBRARIES_ROOT}/build/${ARCHITECTURE_PATH}")
  set(OPENCMISS_LIBRARIES_BINARY_DIR_MPI "${OPENCMISS_LIBRARIES_ROOT}/build/${ARCHITECTURE_PATH_MPI}")
endif ()

# Install tree locations for components (with/without mpi)
if (DEFINED OPENCMISS_ROOT)
  # This is also used in Install.cmake to place the opencmiss config files.
  set(OPENCMISS_COMPONENTS_INSTALL_PREFIX_NO_BUILD_TYPE "${OPENCMISS_INSTALL_ROOT}/${ARCHITECTURE_PATH}")
  # This is the install prefix for all components without mpi
  set(OPENCMISS_COMPONENTS_INSTALL_PREFIX "${OPENCMISS_COMPONENTS_INSTALL_PREFIX_NO_BUILD_TYPE}/${BUILDTYPEEXTRA}")
  # This is the install path for mpi-aware components
  set(OPENCMISS_COMPONENTS_INSTALL_PREFIX_MPI_NO_BUILD_TYPE "${OPENCMISS_INSTALL_ROOT}/${ARCHITECTURE_PATH_MPI}")
  set(OPENCMISS_COMPONENTS_INSTALL_PREFIX_MPI "${OPENCMISS_COMPONENTS_INSTALL_PREFIX_MPI_NO_BUILD_TYPE}/${BUILDTYPEEXTRA}")

  set(OPENCMISS_LIBRARIES_INSTALL_PREFIX_NO_BUILD_TYPE "${OPENCMISS_INSTALL_ROOT}/${ARCHITECTURE_PATH}")
  set(OPENCMISS_LIBRARIES_INSTALL_PREFIX "${OPENCMISS_LIBRARIES_INSTALL_PREFIX_NO_BUILD_TYPE}/${BUILDTYPEEXTRA}")
  set(OPENCMISS_LIBRARIES_INSTALL_PREFIX_MPI_NO_BUILD_TYPE "${OPENCMISS_INSTALL_ROOT}/${ARCHITECTURE_PATH_MPI}")
  set(OPENCMISS_LIBRARIES_INSTALL_PREFIX_MPI "${OPENCMISS_LIBRARIES_INSTALL_PREFIX_MPI_NO_BUILD_TYPE}/${BUILDTYPEEXTRA}")
else ()
  # This is also used in Install.cmake to place the opencmiss config files.
  set(OPENCMISS_COMPONENTS_INSTALL_PREFIX_NO_BUILD_TYPE "${OPENCMISS_DEPENDENCIES_ROOT}/install/${ARCHITECTURE_PATH}")
  # This is the install prefix for all components without mpi
  set(OPENCMISS_COMPONENTS_INSTALL_PREFIX "${OPENCMISS_COMPONENTS_INSTALL_PREFIX_NO_BUILD_TYPE}/${BUILDTYPEEXTRA}")
  # This is the install path for mpi-aware components
  set(OPENCMISS_COMPONENTS_INSTALL_PREFIX_MPI_NO_BUILD_TYPE "${OPENCMISS_DEPENDENCIES_ROOT}/install/${ARCHITECTURE_PATH_MPI}")
  set(OPENCMISS_COMPONENTS_INSTALL_PREFIX_MPI "${OPENCMISS_COMPONENTS_INSTALL_PREFIX_MPI_NO_BUILD_TYPE}/${BUILDTYPEEXTRA}")

  set(OPENCMISS_LIBRARIES_INSTALL_PREFIX_NO_BUILD_TYPE "${OPENCMISS_LIBRARIES_ROOT}/install/${ARCHITECTURE_PATH}")
  set(OPENCMISS_LIBRARIES_INSTALL_PREFIX "${OPENCMISS_LIBRARIES_INSTALL_PREFIX_NO_BUILD_TYPE}/${BUILDTYPEEXTRA}")
  set(OPENCMISS_LIBRARIES_INSTALL_PREFIX_MPI_NO_BUILD_TYPE "${OPENCMISS_LIBRARIES_ROOT}/install/${ARCHITECTURE_PATH_MPI}")
  set(OPENCMISS_LIBRARIES_INSTALL_PREFIX_MPI "${OPENCMISS_LIBRARIES_INSTALL_PREFIX_MPI_NO_BUILD_TYPE}/${BUILDTYPEEXTRA}")
endif ()
