
# Set paths for the OPENCMISS Build.

if (NOT DEFINED OPENCMISS_INSTALL_ROOT)
  set(OPENCMISS_INSTALL_ROOT "${OPENCMISS_ROOT}/install")
endif ()

set(ARCHITECTURE_PATH .)
set(ARCHITECTURE_PATH_MPI .)
if (OC_USE_ARCHITECTURE_PATH)
    getArchitecturePath(ARCHITECTURE_PATH ARCHITECTURE_PATH_MPI)
endif()

# Build tree location for components (with/without mpi)
if (DEFINED OPENCMISS_ROOT)
  SET(OPENCMISS_COMPONENTS_BINARY_DIR "${OPENCMISS_ROOT}/build/${ARCHITECTURE_PATH}")
  SET(OPENCMISS_COMPONENTS_BINARY_DIR_MPI "${OPENCMISS_ROOT}/build/${ARCHITECTURE_PATH_MPI}")
  SET(OPENCMISS_LIBRARIES_BINARY_DIR "${OPENCMISS_ROOT}/build/${ARCHITECTURE_PATH}")
  SET(OPENCMISS_LIBRARIES_BINARY_DIR_MPI "${OPENCMISS_ROOT}/build/${ARCHITECTURE_PATH_MPI}")
else ()
  if (NOT DEFINED OPENCMISS_DEPENDENCIES_ROOT)
    message(FATAL_ERROR "OPENCMISS_ROOT it not defined nor is OPENCMISS_DEPENDENCIES_ROOT one of these must be set.")
  endif ()
  if (NOT DEFINED OPENCMISS_LIBRARIES_ROOT)
    message(FATAL_ERROR "OPENCMISS_ROOT it not defined nor is OPENCMISS_LIBRARIES_ROOT one of these must be set.")
  endif ()

  SET(OPENCMISS_COMPONENTS_BINARY_DIR "${OPENCMISS_DEPENDENCIES_ROOT}-build/${ARCHITECTURE_PATH}")
  SET(OPENCMISS_COMPONENTS_BINARY_DIR_MPI "${OPENCMISS_DEPENDENCIES_ROOT}-build/${ARCHITECTURE_PATH_MPI}")
  SET(OPENCMISS_LIBRARIES_BINARY_DIR "${OPENCMISS_LIBRARIES_ROOT}-build/${ARCHITECTURE_PATH}")
  SET(OPENCMISS_LIBRARIES_BINARY_DIR_MPI "${OPENCMISS_LIBRARIES_ROOT}-build/${ARCHITECTURE_PATH_MPI}")
endif ()


# Install dir
# Extra path segment for single configuration case - will give release/debug/...
getBuildTypePathElem(BUILDTYPEEXTRA)
########### everything from the OpenCMISS main project goes into install/
# This is also used in Install.cmake to place the opencmiss config files.
set(OPENCMISS_COMPONENTS_INSTALL_PREFIX_NO_BUILD_TYPE "${OPENCMISS_INSTALL_ROOT}/${ARCHITECTURE_PATH}")
# This is the install prefix for all components without mpi
set(OPENCMISS_COMPONENTS_INSTALL_PREFIX "${OPENCMISS_COMPONENTS_INSTALL_PREFIX_NO_BUILD_TYPE}/${BUILDTYPEEXTRA}")
# This is the install path for mpi-aware components
set(OPENCMISS_COMPONENTS_INSTALL_PREFIX_MPI_NO_BUILD_TYPE "${OPENCMISS_INSTALL_ROOT}/${ARCHITECTURE_PATH_MPI}")
set(OPENCMISS_COMPONENTS_INSTALL_PREFIX_MPI "${OPENCMISS_COMPONENTS_INSTALL_PREFIX_MPI_NO_BUILD_TYPE}/${BUILDTYPEEXTRA}")

