
if (NOT EXISTS "@ACTIVATE_SCRIPT@")
    execute_process(COMMAND @VIRTUALENV_EXEC@ --system-site-packages "@VIRTUALENV_COMPLETE_INSTALL_PREFIX@")
endif ()

file(TO_NATIVE_PATH "@PACKAGE_BINARY_DIR@" SETUP_PY_DIR)
execute_process(COMMAND @VIRTUALENV_COMPLETE_INSTALL_PREFIX@/@VENV_BINDIR@/pip install --upgrade "${SETUP_PY_DIR}")

